// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXrKAeJW_KNLBfiXMFCbxpNAeH09dDHXg',
    appId: '1:589282512583:web:85510014d8e10c901d38e2',
    messagingSenderId: '589282512583',
    projectId: 'bharghavi-65459',
    authDomain: 'bharghavi-65459.firebaseapp.com',
    storageBucket: 'bharghavi-65459.firebasestorage.app',
    measurementId: 'G-53XYY5P8EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ0xbtaYVChPecYK3DkymfDOlTamG_1Y8',
    appId: '1:589282512583:android:8ca582930e99379b1d38e2',
    messagingSenderId: '589282512583',
    projectId: 'bharghavi-65459',
    storageBucket: 'bharghavi-65459.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvs1hFoso_h3oE-Rk5Fd2Np7_8O_TO6Ds',
    appId: '1:589282512583:ios:9fe9a917739de26a1d38e2',
    messagingSenderId: '589282512583',
    projectId: 'bharghavi-65459',
    storageBucket: 'bharghavi-65459.firebasestorage.app',
    iosBundleId: 'com.example.bharghavi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvs1hFoso_h3oE-Rk5Fd2Np7_8O_TO6Ds',
    appId: '1:589282512583:ios:9fe9a917739de26a1d38e2',
    messagingSenderId: '589282512583',
    projectId: 'bharghavi-65459',
    storageBucket: 'bharghavi-65459.firebasestorage.app',
    iosBundleId: 'com.example.bharghavi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXrKAeJW_KNLBfiXMFCbxpNAeH09dDHXg',
    appId: '1:589282512583:web:cff48626d71259d41d38e2',
    messagingSenderId: '589282512583',
    projectId: 'bharghavi-65459',
    authDomain: 'bharghavi-65459.firebaseapp.com',
    storageBucket: 'bharghavi-65459.firebasestorage.app',
    measurementId: 'G-1ZTD37KR1X',
  );
}
